# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

#variables:
#  solution: '**/*.sln'
#  buildPlatform: 'Any CPU'
#  buildConfiguration: 'Release'

steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

- task: CmdLine@2
  inputs:
    script: |
      echo Installing CycloneDX
      
      dotnet tool install --global CycloneDX
      
      echo CycloneDX installed

- task: CmdLine@2
  inputs:
    script: |
      echo running Cyclonedx
      
      dotnet CycloneDX OrchardCore.sln -o scan --disable-github-licenses
      
      echo CycloneDX Analysis Finished
      
      ls -ltar
      
      ls -ltar scan
#- task: DotNetCoreCLI@2
#  displayName: "Update CycloneDX"
#  inputs:
#    command: 'custom'
#    custom: 'tool'
#    arguments: 'install CycloneDX -g'
#    includeNuGetOrg: true
  
    
#- task: DotNetCoreCLI@2
#  displayName: "Generate CycloneDX SBOM"
#  inputs:
#    command: 'custom'
#    custom: 'CycloneDX'
#    arguments: 'WebGoat.NET.sln --out scan'
#    includeNuGetOrg: true

- task: NexusIqPipelineTask@1
  displayName: "IQ server"
  inputs:
    nexusIqService: 'nexus'
    applicationId: 'webgoat1'
    stage: 'Build'
    scanTargets: 'scan\*'

- task: PowerShell@2
  displayName: "Results Output"
  inputs:
    targetType: 'inline'
    script: |
      $results = Get-ChildItem "D:\a\_tasks\*\*\resources\evaluationResult.json" | Get-Content | ConvertTo-Json
      Write-Host "Nexus Evaluation Results = $($results)"